# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
# ad108162-8731-402e-9b07-d014c9f6d04a
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/37cdc637-c86c-4856-82cc-af29c48273ea";
      fsType = "ext4";
    };
  fileSystems."/extra-store" =
    { device = "/dev/disk/by-uuid/5b062b07-f74b-4016-b4e3-28bcf7c53381";
      fsType = "ext4";
    };
  fileSystems."/extra-store-2" =
    { device = "/dev/disk/by-uuid/9113fdd9-2e5c-4502-85b5-ada1445a5c19";
      fsType = "ext4";
    };



  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/E602-05F9";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/b66cc615-7c81-4ed1-85fd-cf5a2b6750ae"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp5s0.useDHCP = lib.mkDefault true;

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
